services:
  - type: web
    name: fastapi-trajectory
    runtime: python
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
